spring.application.name=auth-server
server.port=9000

# ========================================
# Authorization Server
# ========================================
spring.security.oauth2.authorizationserver.issuer=http://localhost:9000

# ========================================
# Logging
# ========================================
logging.level.root=INFO
logging.level.org.springframework.security=INFO
logging.level.org.springframework.security.oauth2=INFO