spring.application.name=bff-atm

server.port=8084

backend-core.url=http://localhost:8081

spring.cloud.openfeign.client.config.backend-core.connectTimeout=2000
spring.cloud.openfeign.client.config.backend-core.readTimeout=5000